# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kdef < Formula
  desc "Declarative resource management for Kafka"
  homepage "https://github.com/peter-evans/kdef"
  version "0.5.6"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/peter-evans/kdef/releases/download/v0.5.6/kdef_0.5.6_darwin_x86_64.tar.gz"
      sha256 "f81cab0cd0e336e8bcc85ece5b36287879d7d399037402a81bdfa153911afa87"

      def install
        bin.install "kdef"
      end
    end
    on_arm do
      url "https://github.com/peter-evans/kdef/releases/download/v0.5.6/kdef_0.5.6_darwin_arm64.tar.gz"
      sha256 "4e70f6b49061d3d14bd0bcfbfef25d020bfd4a0b0f7ffd7d3e5e89e1f6e2ab5b"

      def install
        bin.install "kdef"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/peter-evans/kdef/releases/download/v0.5.6/kdef_0.5.6_linux_x86_64.tar.gz"
        sha256 "cb470f047da23f01d287736602ff142cc0f199aee401861083415359f73f59d6"

        def install
          bin.install "kdef"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/peter-evans/kdef/releases/download/v0.5.6/kdef_0.5.6_linux_arm64.tar.gz"
        sha256 "1d372d71650f42cbb16af78e4cc87a7258e682dceb1cb73ebe3ae435f1a3eee5"

        def install
          bin.install "kdef"
        end
      end
    end
  end

  test do
    system "#{bin}/kdef --version"
  end
end
