# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kdef < Formula
  desc "Declarative resource management for Kafka"
  homepage "https://github.com/peter-evans/kdef"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/peter-evans/kdef/releases/download/v0.0.2/kdef_0.0.2_darwin_arm64.tar.gz"
      sha256 "02f9b2be79493345cffd027811d6eabf328874b27fcd0f904058f1cd3660de21"

      def install
        bin.install "kdef"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/peter-evans/kdef/releases/download/v0.0.2/kdef_0.0.2_darwin_x86_64.tar.gz"
      sha256 "927c3557bcbccfcbbbdc5b097b87db07fef243abe2cb031983150cbaa676384a"

      def install
        bin.install "kdef"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/peter-evans/kdef/releases/download/v0.0.2/kdef_0.0.2_linux_x86_64.tar.gz"
      sha256 "645b1ad243a745d01a22d5aaad09bed69b763e72e3466ab940bca5bd9c496d7d"

      def install
        bin.install "kdef"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/peter-evans/kdef/releases/download/v0.0.2/kdef_0.0.2_linux_arm64.tar.gz"
      sha256 "19831a2d2aef972aed873b5b2c3e05810356732f67afad871fd070ef49ac42d6"

      def install
        bin.install "kdef"
      end
    end
  end

  test do
    system "#{bin}/kdef --version"
  end
end
