# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kdef < Formula
  desc "Declarative resource management for Kafka"
  homepage "https://github.com/peter-evans/kdef"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/peter-evans/kdef/releases/download/v0.2.3/kdef_0.2.3_darwin_arm64.tar.gz"
      sha256 "a09d0178e9baf1c175b33831008d9065f439cdae2cce799e4f4755cdbeb14364"

      def install
        bin.install "kdef"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/peter-evans/kdef/releases/download/v0.2.3/kdef_0.2.3_darwin_x86_64.tar.gz"
      sha256 "56014e6d3cb937be5c6d06d371bd6da09ab43270d9d5ffd1dddce0e0447bfa8c"

      def install
        bin.install "kdef"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/peter-evans/kdef/releases/download/v0.2.3/kdef_0.2.3_linux_arm64.tar.gz"
      sha256 "b905e3c53dff1e1b8cd63622bf44867cc2bfa31e1b285757bde12a5f082fd621"

      def install
        bin.install "kdef"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/peter-evans/kdef/releases/download/v0.2.3/kdef_0.2.3_linux_x86_64.tar.gz"
      sha256 "78cdfb3e0fe910eb3f126f41349b44ed700bdbdb994037d1cca3ae3e3c7447ca"

      def install
        bin.install "kdef"
      end
    end
  end

  test do
    system "#{bin}/kdef --version"
  end
end
